# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogoCurso2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class DialogoP(object):
    def setupUi(self, DialogoPandas):
        DialogoPandas.setObjectName("DialogoPandas")
        DialogoPandas.resize(871, 613)
        DialogoPandas.setFixedSize(871, 613)
        DialogoPandas.setStyleSheet("QMainWindow {\n"
"    background-color:#f0f0f0;\n"
"}\n"
"QCheckBox {\n"
"    padding:2px;\n"
"}\n"
"QCheckBox:hover {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    border-width:1px;\n"
"    padding-left: 1px;\n"
"    padding-right: 1px;\n"
"    padding-bottom: 1px;\n"
"    padding-top: 1px;\n"
"    border-color: rgb(255,150,60);\n"
"    background-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(190, 90, 50, 50), stop:1 rgba(250, 130, 40, 50));\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    border-width:1px;\n"
"    border-color: rgb(246, 134, 86);\n"
"      background-color:rgb(246, 134, 86)\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    border-width:1px;\n"
"    border-color:rgb(246, 134, 86);\n"
"      background-color:rgb(255,255,255);\n"
"}\n"
"QColorDialog {\n"
"    background-color:#f0f0f0;\n"
"}\n"
"QComboBox {\n"
"    color:rgb(81,72,65);\n"
"    background: #ffffff;\n"
"}\n"
"QComboBox:editable {\n"
"    background: #ffffff;\n"
"    color: rgb(81,72,65);\n"
"    selection-color:rgb(81,72,65);\n"
"    selection-background-color: #ffffff;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color:rgb(81,72,65);    \n"
"    background: #ffffff;\n"
"    selection-color: #ffffff;\n"
"    selection-background-color: rgb(246, 134, 86);\n"
"}\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    color:  #1e1d23;    \n"
"    background: #ffffff;\n"
"}\n"
"QDateTimeEdit {\n"
"    color:rgb(81,72,65);\n"
"    background-color: #ffffff;\n"
"}\n"
"QDateEdit {\n"
"    color:rgb(81,72,65);\n"
"    background-color: #ffffff;\n"
"}\n"
"QDialog {\n"
"    background-color:#f0f0f0;\n"
"}\n"
"QDoubleSpinBox {\n"
"    color:rgb(81,72,65);\n"
"    background-color: #ffffff;\n"
"}\n"
"QFontComboBox {\n"
"    color:rgb(81,72,65);\n"
"    background-color: #ffffff;\n"
"}\n"
"QLabel {\n"
"    color:rgb(17,17,17);\n"
"}\n"
"QLineEdit {\n"
"    background-color:rgb(255,255,255);\n"
"    selection-background-color:rgb(236,116,64);\n"
"    color:rgb(17,17,17);\n"
"}\n"
"QMenuBar {\n"
"    color:rgb(223,219,210);\n"
"    background-color:rgb(65,64,59);\n"
"}\n"
"QMenuBar::item {\n"
"    padding-top:4px;\n"
"    padding-left:4px;\n"
"    padding-right:4px;\n"
"    color:rgb(223,219,210);\n"
"    background-color:rgb(65,64,59);\n"
"}\n"
"QMenuBar::item:selected {\n"
"    color:rgb(255,255,255);\n"
"    padding-top:2px;\n"
"    padding-left:2px;\n"
"    padding-right:2px;\n"
"    border-top-width:2px;\n"
"    border-left-width:2px;\n"
"    border-right-width:2px;\n"
"    border-top-right-radius:4px;\n"
"    border-top-left-radius:4px;\n"
"    border-style:solid;\n"
"    background-color:rgb(65,64,59);\n"
"    border-top-color: rgb(47,47,44);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(90, 87, 78, 255), stop:1 rgba(47,47,44, 255));\n"
"    border-left-color:  qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(90, 87, 78, 255), stop:1 rgba(47,47,44, 255));\n"
"}\n"
"QMenu {\n"
"    color:rgb(223,219,210);\n"
"    background-color:rgb(65,64,59);\n"
"}\n"
"QMenu::item {\n"
"    color:rgb(223,219,210);\n"
"    padding-left:20px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    padding-right:10px;\n"
"}\n"
"QMenu::item:selected {\n"
"    color:rgb(255,255,255);\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(225, 108, 54, 255), stop:1 rgba(246, 134, 86, 255));\n"
"    border-style:solid;\n"
"    border-width:3px;\n"
"    padding-left:17px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    padding-right:7px;\n"
"    border-bottom-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(175,85,48,255), stop:1 rgba(236,114,67, 255));\n"
"    border-top-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"    border-right-color:qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"    border-left-color:qlineargradient(spread:pad, x1:1, y1:0.5, x2:0, y2:0.5, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"}\n"
"QPlainTextEdit {\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color:transparent;\n"
"    color:rgb(17,17,17);\n"
"    selection-background-color:rgb(236,116,64);\n"
"}\n"
"QProgressBar {\n"
"    text-align: center;\n"
"    color: rgb(0, 0, 0);\n"
"    border-width: 1px; \n"
"    border-radius: 10px;\n"
"    border-style: inset;\n"
"    border-color: rgb(150,150,150);\n"
"    background-color:rgb(221,221,219);\n"
"}\n"
"QProgressBar::chunk:horizontal {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(225, 108, 54, 255), stop:1 rgba(246, 134, 86, 255));\n"
"    border-style: solid;\n"
"    border-radius:8px;\n"
"    border-width:1px;\n"
"    border-bottom-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(175,85,48,255), stop:1 rgba(236,114,67, 255));\n"
"    border-top-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"    border-right-color:qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"    border-left-color:qlineargradient(spread:pad, x1:1, y1:0.5, x2:0, y2:0.5, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"}\n"
"QPushButton{\n"
"    color:rgb(17,17,17);\n"
"    border-width: 1px;\n"
"    border-radius: 6px;\n"
"    border-bottom-color: rgb(150,150,150);\n"
"    border-right-color: rgb(165,165,165);\n"
"    border-left-color: rgb(165,165,165);\n"
"    border-top-color: rgb(180,180,180);\n"
"    border-style: solid;\n"
"    padding: 4px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(220, 220, 220, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QPushButton:hover{\n"
"    color:rgb(17,17,17);\n"
"    border-width: 1px;\n"
"    border-radius:6px;\n"
"    border-top-color: rgb(255,150,60);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 255));\n"
"    border-left-color:  qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 255));\n"
"    border-bottom-color: rgb(200,70,20);\n"
"    border-style: solid;\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(220, 220, 220, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QPushButton:default{\n"
"    color:rgb(17,17,17);\n"
"    border-width: 1px;\n"
"    border-radius:6px;\n"
"    border-top-color: rgb(255,150,60);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 255));\n"
"    border-left-color:  qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 255));\n"
"    border-bottom-color: rgb(200,70,20);\n"
"    border-style: solid;\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(220, 220, 220, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QPushButton:pressed{\n"
"    color:rgb(17,17,17);\n"
"    border-width: 1px;\n"
"    border-radius: 6px;\n"
"    border-width: 1px;\n"
"    border-top-color: rgba(255,150,60,200);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 200));\n"
"    border-left-color:  qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 200));\n"
"    border-bottom-color: rgba(200,70,20,200);\n"
"    border-style: solid;\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(220, 220, 220, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QPushButton:disabled{\n"
"    color:rgb(174,167,159);\n"
"    border-width: 1px;\n"
"    border-radius: 6px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(200, 200, 200, 255), stop:1 rgba(230, 230, 230, 255));\n"
"}\n"
"QRadioButton {\n"
"    padding: 1px;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: rgba(246, 134, 86, 255);\n"
"    color: #a9b7c6;\n"
"    background-color:rgba(246, 134, 86, 255);\n"
"}\n"
"QRadioButton::indicator:!checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: rgb(246, 134, 86);\n"
"    color: #a9b7c6;\n"
"    background-color: transparent;\n"
"}\n"
"QScrollArea {\n"
"    color: #FFFFFF;\n"
"    background-color:#f0f0f0;\n"
"}\n"
"QSlider::groove {\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    height: 5px;\n"
"    background: rgb(246, 134, 86);\n"
"}\n"
"QSlider::groove:vertical {\n"
"    width: 5px;\n"
"    background: rgb(246, 134, 86);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    width: 12px;\n"
"    margin: -5px 0;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    height: 12px;\n"
"    margin: 0 -5px;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::add-page:horizontal {\n"
"     background: white;\n"
"}\n"
"QSlider::add-page:vertical {\n"
"    background: white;\n"
"}\n"
"QSlider::sub-page:horizontal {\n"
"    background: rgb(246, 134, 86);\n"
"}\n"
"QSlider::sub-page:vertical {\n"
"      background: rgb(246, 134, 86);\n"
"}\n"
"QStatusBar {\n"
"    color:rgb(81,72,65);\n"
"}\n"
"QSpinBox {\n"
"    color:rgb(81,72,65);\n"
"    background-color: #ffffff;\n"
"}\n"
"QScrollBar:horizontal {\n"
"    max-height: 20px;\n"
"    border: 1px transparent grey;\n"
"    margin: 0px 20px 0px 20px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    border-radius: 7px;\n"
"    min-width: 25px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(255,150,60);\n"
"    border-radius: 7px;\n"
"    min-width: 25px;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"      border: 1px solid;\n"
"      border-color: rgb(207,207,207);\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-right-radius: 7px;\n"
"      background: rgb(255, 255, 255);\n"
"      width: 20px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:hover {\n"
"      border: 1px solid;\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-right-radius: 7px;\n"
"      border-color: rgb(255,150,60);\n"
"      background: rgb(255, 255, 255);\n"
"      width: 20px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed {\n"
"      border: 1px solid grey;\n"
"      border-top-left-radius: 7px;\n"
"      border-top-right-radius: 7px;\n"
"      border-bottom-right-radius: 7px;\n"
"      background: rgb(231,231,231);\n"
"      width: 20px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"      border: 1px solid;\n"
"      border-color: rgb(207,207,207);\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-left-radius: 7px;\n"
"      background: rgb(255, 255, 255);\n"
"      width: 20px;\n"
"      subcontrol-position: left;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {\n"
"      border: 1px solid;\n"
"      border-color: rgb(255,150,60);\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-left-radius: 7px;\n"
"      background: rgb(255, 255, 255);\n"
"      width: 20px;\n"
"      subcontrol-position: left;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {\n"
"      border: 1px solid grey;\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-left-radius: 7px;\n"
"      background: rgb(231,231,231);\n"
"      width: 20px;\n"
"      subcontrol-position: left;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::left-arrow:horizontal {\n"
"      border: 1px transparent grey;\n"
"      border-top-left-radius: 3px;\n"
"      border-bottom-left-radius: 3px;\n"
"      width: 6px;\n"
"      height: 6px;\n"
"      background: rgb(230,230,230);\n"
"}\n"
"QScrollBar::right-arrow:horizontal {\n"
"    border: 1px transparent grey;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"      width: 6px;\n"
"      height: 6px;\n"
"     background: rgb(230,230,230);\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"     background: none;\n"
"} \n"
"QScrollBar:vertical {\n"
"    max-width: 20px;\n"
"    border: 1px transparent grey;\n"
"    margin: 20px 0px 20px 0px;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    border: 1px solid;\n"
"    border-color: rgb(207,207,207);\n"
"    border-bottom-right-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-top-left-radius: 7px;\n"
"    background: rgb(255, 255, 255);\n"
"      height: 20px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {\n"
"      border: 1px solid;\n"
"      border-color: rgb(255,150,60);\n"
"      border-bottom-right-radius: 7px;\n"
"      border-bottom-left-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      background: rgb(255, 255, 255);\n"
"      height: 20px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {\n"
"      border: 1px solid grey;\n"
"      border-bottom-left-radius: 7px;\n"
"      border-bottom-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      background: rgb(231,231,231);\n"
"      height: 20px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"      border: 1px solid;\n"
"      border-color: rgb(207,207,207);\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-left-radius: 7px;\n"
"      background: rgb(255, 255, 255);\n"
"      height: 20px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {\n"
"      border: 1px solid;\n"
"      border-color: rgb(255,150,60);\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-left-radius: 7px;\n"
"    background: rgb(255, 255, 255);\n"
"      height: 20px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {\n"
"      border: 1px solid grey;\n"
"      border-top-left-radius: 7px;\n"
"      border-top-right-radius: 7px;\n"
"      background: rgb(231,231,231);\n"
"     height: 20px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    border-radius: 7px;\n"
"    min-height: 25px;\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(255,150,60);\n"
"    border-radius: 7px;\n"
"    min-height: 25px;\n"
"}\n"
"QScrollBar::up-arrow:vertical {\n"
"    border: 1px transparent grey;\n"
"      border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"      width: 6px;\n"
"      height: 6px;\n"
"      background: rgb(230,230,230);\n"
"}\n"
"QScrollBar::down-arrow:vertical {\n"
"      border: 1px transparent grey;\n"
"      border-bottom-left-radius: 3px;\n"
"      border-bottom-right-radius: 3px;\n"
"      width: 6px;\n"
"      height: 6px;\n"
"      background: rgb(230,230,230);\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"      background: none;\n"
"}\n"
"QTabWidget {\n"
"    color:rgb(0,0,0);\n"
"    background-color:rgb(247,246,246);\n"
"}\n"
"QTabWidget::pane {\n"
"    border-color: rgb(180,180,180);\n"
"    background-color:rgb(247,246,246);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"      border-radius: 6px;\n"
"}\n"
"QTabBar::tab {\n"
"    padding-left:4px;\n"
"    padding-right:4px;\n"
"    padding-bottom:2px;\n"
"    padding-top:2px;\n"
"    color:rgb(81,72,65);\n"
"      background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(221,218,217,255), stop:1 rgba(240,239,238,255));\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"      border-top-right-radius:4px;\n"
"    border-top-left-radius:4px;\n"
"    border-top-color: rgb(180,180,180);\n"
"    border-left-color: rgb(180,180,180);\n"
"    border-right-color: rgb(180,180,180);\n"
"    border-bottom-color: transparent;\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:last:selected, QTabBar::tab:hover {\n"
"      background-color:rgb(247,246,246);\n"
"      margin-left: 0px;\n"
"      margin-right: 1px;\n"
"}\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 1px;\n"
"    margin-right: 1px;\n"
"}\n"
"QTextEdit {\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color:transparent;\n"
"    color:rgb(17,17,17);\n"
"    selection-background-color:rgb(236,116,64);\n"
"}\n"
"QTimeEdit {\n"
"    color:rgb(81,72,65);\n"
"    background-color: #ffffff;\n"
"}\n"
"QToolBox {\n"
"    color:rgb(81,72,65);\n"
"    background-color: #ffffff;\n"
"}\n"
"QToolBox::tab {\n"
"    color:rgb(81,72,65);\n"
"    background-color: #ffffff;\n"
"}\n"
"QToolBox::tab:selected {\n"
"    color:rgb(81,72,65);\n"
"    background-color: #ffffff;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(DialogoPandas)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_head = QtWidgets.QLabel(self.centralwidget)
        self.lbl_head.setGeometry(QtCore.QRect(10, 30, 531, 16))
        font = QtGui.QFont()
        font.setFamily("Ebrima")
        self.lbl_head.setFont(font)
        self.lbl_head.setText("")
        self.lbl_head.setObjectName("lbl_head")
        self.tbv_1 = QtWidgets.QTableView(self.centralwidget)
        self.tbv_1.setGeometry(QtCore.QRect(10, 50, 851, 191))
        self.tbv_1.setObjectName("tbv_1")
        self.gbx_graficos = QtWidgets.QGroupBox(self.centralwidget)
        self.gbx_graficos.setGeometry(QtCore.QRect(10, 250, 851, 101))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gbx_graficos.setFont(font)
        self.gbx_graficos.setObjectName("gbx_graficos")
        self.cbx_matriz = QtWidgets.QCheckBox(self.gbx_graficos)
        self.cbx_matriz.setGeometry(QtCore.QRect(40, 20, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.cbx_matriz.setFont(font)
        self.cbx_matriz.setObjectName("cbx_matriz")
        self.cbx_cualitativas = QtWidgets.QCheckBox(self.gbx_graficos)
        self.cbx_cualitativas.setGeometry(QtCore.QRect(40, 44, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.cbx_cualitativas.setFont(font)
        self.cbx_cualitativas.setObjectName("cbx_cualitativas")
        self.cbx_correlaciones = QtWidgets.QCheckBox(self.gbx_graficos)
        self.cbx_correlaciones.setGeometry(QtCore.QRect(310, 30, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.cbx_correlaciones.setFont(font)
        self.cbx_correlaciones.setObjectName("cbx_correlaciones")
        self.cbx_numericas = QtWidgets.QCheckBox(self.gbx_graficos)
        self.cbx_numericas.setGeometry(QtCore.QRect(40, 70, 211, 20))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.cbx_numericas.setFont(font)
        self.cbx_numericas.setObjectName("cbx_numericas")
        self.label_2 = QtWidgets.QLabel(self.gbx_graficos)
        self.label_2.setGeometry(QtCore.QRect(463, 10, 271, 16))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.combo_grafico = QtWidgets.QComboBox(self.gbx_graficos)
        self.combo_grafico.setEnabled(False)
        self.combo_grafico.setGeometry(QtCore.QRect(480, 30, 201, 22))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setBold(True)
        font.setWeight(75)
        self.combo_grafico.setFont(font)
        self.combo_grafico.setObjectName("combo_grafico")
        self.cbx_dispersiones = QtWidgets.QCheckBox(self.gbx_graficos)
        self.cbx_dispersiones.setGeometry(QtCore.QRect(310, 60, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.cbx_dispersiones.setFont(font)
        self.cbx_dispersiones.setObjectName("cbx_dispersiones")
        self.combo_grafico_dispersiones = QtWidgets.QComboBox(self.gbx_graficos)
        self.combo_grafico_dispersiones.setEnabled(False)
        self.combo_grafico_dispersiones.setGeometry(QtCore.QRect(480, 60, 201, 22))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setBold(True)
        font.setWeight(75)
        self.combo_grafico_dispersiones.setFont(font)
        self.combo_grafico_dispersiones.setObjectName("combo_grafico_dispersiones")
        self.btn_graficar = QtWidgets.QPushButton(self.gbx_graficos)
        self.btn_graficar.setEnabled(False)
        self.btn_graficar.setGeometry(QtCore.QRect(710, 40, 121, 31))
        self.btn_graficar.setObjectName("btn_graficar")
        self.gbx_calculos = QtWidgets.QGroupBox(self.centralwidget)
        self.gbx_calculos.setGeometry(QtCore.QRect(10, 360, 851, 171))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gbx_calculos.setFont(font)
        self.gbx_calculos.setObjectName("gbx_calculos")
        self.label_3 = QtWidgets.QLabel(self.gbx_calculos)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 191, 16))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.combo_variable = QtWidgets.QComboBox(self.gbx_calculos)
        self.combo_variable.setEnabled(False)
        self.combo_variable.setGeometry(QtCore.QRect(260, 20, 141, 22))
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.combo_variable.setFont(font)
        self.combo_variable.setObjectName("combo_variable")
        self.label_6 = QtWidgets.QLabel(self.gbx_calculos)
        self.label_6.setGeometry(QtCore.QRect(10, 40, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.rbt_forest = QtWidgets.QRadioButton(self.gbx_calculos)
        self.rbt_forest.setEnabled(True)
        self.rbt_forest.setGeometry(QtCore.QRect(50, 60, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setBold(False)
        font.setWeight(50)
        self.rbt_forest.setFont(font)
        self.rbt_forest.setAutoExclusive(True)
        self.rbt_forest.setObjectName("rbt_forest")
        self.rbt_ridge = QtWidgets.QRadioButton(self.gbx_calculos)
        self.rbt_ridge.setEnabled(True)
        self.rbt_ridge.setGeometry(QtCore.QRect(160, 60, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setBold(False)
        font.setWeight(50)
        self.rbt_ridge.setFont(font)
        self.rbt_ridge.setChecked(False)
        self.rbt_ridge.setObjectName("rbt_ridge")
        self.rbt_knn = QtWidgets.QRadioButton(self.gbx_calculos)
        self.rbt_knn.setEnabled(True)
        self.rbt_knn.setGeometry(QtCore.QRect(268, 60, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setBold(False)
        font.setWeight(50)
        self.rbt_knn.setFont(font)
        self.rbt_knn.setObjectName("rbt_knn")
        self.cbx_distribucion_teorica = QtWidgets.QCheckBox(self.gbx_calculos)
        self.cbx_distribucion_teorica.setGeometry(QtCore.QRect(20, 99, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        self.cbx_distribucion_teorica.setFont(font)
        self.cbx_distribucion_teorica.setObjectName("cbx_distribucion_teorica")
        self.label_9 = QtWidgets.QLabel(self.gbx_calculos)
        self.label_9.setGeometry(QtCore.QRect(10, 80, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.groupBox = QtWidgets.QGroupBox(self.gbx_calculos)
        self.groupBox.setGeometry(QtCore.QRect(560, 20, 281, 141))
        self.groupBox.setObjectName("groupBox")
        self.txt_test = QtWidgets.QLineEdit(self.groupBox)
        self.txt_test.setGeometry(QtCore.QRect(138, 17, 131, 22))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.txt_test.setFont(font)
        self.txt_test.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.txt_test.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_test.setClearButtonEnabled(True)
        self.txt_test.setObjectName("txt_test")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(9, 53, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.txt_excel = QtWidgets.QLineEdit(self.groupBox)
        self.txt_excel.setGeometry(QtCore.QRect(138, 50, 131, 22))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setBold(False)
        font.setWeight(50)
        self.txt_excel.setFont(font)
        self.txt_excel.setPlaceholderText("")
        self.txt_excel.setClearButtonEnabled(True)
        self.txt_excel.setObjectName("txt_excel")
        self.txt_texto = QtWidgets.QLineEdit(self.groupBox)
        self.txt_texto.setGeometry(QtCore.QRect(139, 105, 131, 22))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        self.txt_texto.setFont(font)
        self.txt_texto.setClearButtonEnabled(True)
        self.txt_texto.setObjectName("txt_texto")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 110, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.cbx_descriptivas = QtWidgets.QCheckBox(self.groupBox)
        self.cbx_descriptivas.setGeometry(QtCore.QRect(50, 80, 191, 17))
        self.cbx_descriptivas.setObjectName("cbx_descriptivas")
        self.label_11 = QtWidgets.QLabel(self.gbx_calculos)
        self.label_11.setGeometry(QtCore.QRect(29, 142, 301, 16))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(7)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.cbx_pandas = QtWidgets.QCheckBox(self.gbx_calculos)
        self.cbx_pandas.setGeometry(QtCore.QRect(385, 100, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        self.cbx_pandas.setFont(font)
        self.cbx_pandas.setObjectName("cbx_pandas")
        self.rbt_regresion = QtWidgets.QRadioButton(self.gbx_calculos)
        self.rbt_regresion.setEnabled(True)
        self.rbt_regresion.setGeometry(QtCore.QRect(339, 60, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setBold(False)
        font.setWeight(50)
        self.rbt_regresion.setFont(font)
        self.rbt_regresion.setChecked(False)
        self.rbt_regresion.setObjectName("rbt_regresion")
        self.label_10 = QtWidgets.QLabel(self.gbx_calculos)
        self.label_10.setGeometry(QtCore.QRect(30, 130, 401, 16))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(7)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.cbx_distribucion_kstest = QtWidgets.QCheckBox(self.gbx_calculos)
        self.cbx_distribucion_kstest.setGeometry(QtCore.QRect(183, 100, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        self.cbx_distribucion_kstest.setFont(font)
        self.cbx_distribucion_kstest.setObjectName("cbx_distribucion_kstest")
        self.rbt_ninguno = QtWidgets.QRadioButton(self.gbx_calculos)
        self.rbt_ninguno.setEnabled(True)
        self.rbt_ninguno.setGeometry(QtCore.QRect(470, 60, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setBold(False)
        font.setWeight(50)
        self.rbt_ninguno.setFont(font)
        self.rbt_ninguno.setChecked(True)
        self.rbt_ninguno.setObjectName("rbt_ninguno")
        self.btn_calcular = QtWidgets.QPushButton(self.centralwidget)
        self.btn_calcular.setEnabled(False)
        self.btn_calcular.setGeometry(QtCore.QRect(226, 540, 181, 31))
        self.btn_calcular.setObjectName("btn_calcular")
        self.btn_salir = QtWidgets.QPushButton(self.centralwidget)
        self.btn_salir.setGeometry(QtCore.QRect(446, 540, 181, 31))
        self.btn_salir.setObjectName("btn_salir")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(14, 5, 461, 21))
        font = QtGui.QFont()
        font.setFamily("Ebrima")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        DialogoPandas.setCentralWidget(self.centralwidget)
        self.menu = QtWidgets.QMenuBar(DialogoPandas)
        self.menu.setGeometry(QtCore.QRect(0, 0, 871, 20))
        self.menu.setObjectName("menu")
        self.menuArchivo = QtWidgets.QMenu(self.menu)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuInformacion = QtWidgets.QMenu(self.menu)
        self.menuInformacion.setObjectName("menuInformacion")
        DialogoPandas.setMenuBar(self.menu)
        self.statusbar = QtWidgets.QStatusBar(DialogoPandas)
        self.statusbar.setObjectName("statusbar")
        DialogoPandas.setStatusBar(self.statusbar)
        self.abrir = QtWidgets.QAction(DialogoPandas)
        self.abrir.setObjectName("abrir")
        self.acerca = QtWidgets.QAction(DialogoPandas)
        self.acerca.setObjectName("acerca")
        self.menuArchivo.addAction(self.abrir)
        self.menuInformacion.addAction(self.acerca)
        self.menu.addAction(self.menuArchivo.menuAction())
        self.menu.addAction(self.menuInformacion.menuAction())

        self.retranslateUi(DialogoPandas)
        QtCore.QMetaObject.connectSlotsByName(DialogoPandas)

    def retranslateUi(self, DialogoPandas):
        _translate = QtCore.QCoreApplication.translate
        DialogoPandas.setWindowTitle(_translate("DialogoPandas", "Pandas básico"))
        self.gbx_graficos.setTitle(_translate("DialogoPandas", "GRÁFICOS"))
        self.cbx_matriz.setText(_translate("DialogoPandas", "Matriz de correlación"))
        self.cbx_cualitativas.setText(_translate("DialogoPandas", "Distribución de variables cualitativas"))
        self.cbx_correlaciones.setText(_translate("DialogoPandas", "Gráfico de correlaciones"))
        self.cbx_numericas.setText(_translate("DialogoPandas", "Distribución de variables numéricas"))
        self.label_2.setText(_translate("DialogoPandas", "Seleccione la variable a graficar: "))
        self.cbx_dispersiones.setText(_translate("DialogoPandas", "Gráfico de dispersiones"))
        self.btn_graficar.setText(_translate("DialogoPandas", "Graficar"))
        self.gbx_calculos.setTitle(_translate("DialogoPandas", "CÁLCULOS"))
        self.label_3.setText(_translate("DialogoPandas", "Seleccione la variable de estudio: "))
        self.label_6.setText(_translate("DialogoPandas", "Métodos:"))
        self.rbt_forest.setText(_translate("DialogoPandas", "Random forest"))
        self.rbt_ridge.setText(_translate("DialogoPandas", "Ridge y Lasso"))
        self.rbt_knn.setText(_translate("DialogoPandas", "kNN"))
        self.cbx_distribucion_teorica.setText(_translate("DialogoPandas", "Distribución de los datos"))
        self.label_9.setText(_translate("DialogoPandas", "Extra:"))
        self.groupBox.setTitle(_translate("DialogoPandas", "Opciones"))
        self.txt_test.setText(_translate("DialogoPandas", "0.20"))
        self.label.setText(_translate("DialogoPandas", "test_size del modelo:"))
        self.label_8.setText(_translate("DialogoPandas", "Nombre del excel*: "))
        self.txt_excel.setText(_translate("DialogoPandas", "predicciones.xlsx"))
        self.txt_texto.setText(_translate("DialogoPandas", "regresion.txt"))
        self.label_7.setText(_translate("DialogoPandas", "Nombre del txt**: "))
        self.cbx_descriptivas.setText(_translate("DialogoPandas", "Estadisticas descriptivas en excel"))
        self.label_11.setText(_translate("DialogoPandas", "** Para el caso de una regresión lineal se genera un archivo txt."))
        self.cbx_pandas.setText(_translate("DialogoPandas", "Resumen (dashboard)"))
        self.rbt_regresion.setText(_translate("DialogoPandas", "Regresión lineal**"))
        self.label_10.setText(_translate("DialogoPandas", "*No es necesario cambiar el nombre, pero es recomendable para identificar el modelo usado."))
        self.cbx_distribucion_kstest.setText(_translate("DialogoPandas", "Distribución de los datos (Kstest)"))
        self.rbt_ninguno.setText(_translate("DialogoPandas", "Ninguno"))
        self.btn_calcular.setText(_translate("DialogoPandas", "Calcular"))
        self.btn_salir.setText(_translate("DialogoPandas", "Salir"))
        self.label_4.setText(_translate("DialogoPandas", "Primero debes seleccionar un archivo csv para comenzar a usar la interfaz. "))
        self.menuArchivo.setTitle(_translate("DialogoPandas", "Archivo"))
        self.menuInformacion.setTitle(_translate("DialogoPandas", "Informacion"))
        self.abrir.setText(_translate("DialogoPandas", "Abrir"))
        self.acerca.setText(_translate("DialogoPandas", "Acerca de ..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogoPandas = QtWidgets.QMainWindow()
    ui = DialogoP()
    ui.setupUi(DialogoPandas)
    DialogoPandas.show()
    sys.exit(app.exec_())
